### ISSUE TITLE
Release object_recognition_msgs to Noetic?

### ISSUE THREAD

**Issue by sloretz** [wg-perception/object_recognition_msgs#10]
Would you mind releasing `object_recognition_msgs` to ROS Noetic? It looks like all of its dependencies have been released, and recursively 45 repos need it.

I'm not sure how much work it will need. At a minimum it needs #9.

**Comment by sloretz** [comment]
@vrabaud friendly ping :)

**Comment by sloretz** [comment]
Friendly ping, anyone in `wg-perception`  planning on releasing this into ROS Noetic? @vrabaud, @jonbinney, @dgossow randomly pinging your names [out of the 16 org members](https://github.com/orgs/wg-perception/people).

**Comment by jonbinney** [comment]
Released: https://github.com/ros/rosdistro/pull/24547
