### ISSUE TITLE
Release into ROS2 Galactic

### ISSUE THREAD

**Issue by DLu** [wg-perception/object_recognition_msgs#12]

**Comment by vatanaksoytezer** [comment]
Friendly ping to @jonbinney . We are trying to release moveit for galactic and rolling. We've compiled `object_recognition_msgs` on both and using without any issues. Can we get a release on these distros if you are available?

**Comment by DLu** [comment]
I think @vrabaud is the maintainer now

**Comment by jonbinney** [comment]
Sorry for the slow response! I'm not the maintainer but if @vrabaud is busy I can go ahead and do a release to unblock people who need this. @vatanaksoytezer are you using the ros2 branch of this repo without any modifications?

**Comment by vatanaksoytezer** [comment]
No worries at all, thanks a lot for unblocking us! We are currently using the ros2 branch without any modifications. @jonbinney

**Comment by jonbinney** [comment]
Done! Will still take some time for the rosdistro PRs to get merged and for the buildfarm to build. Here are the rosdistro PRs:

Galactic release: https://github.com/ros/rosdistro/pull/29723
Rolling release: https://github.com/ros/rosdistro/pull/29724

**Comment by DLu** [comment]
![thanks](https://media.giphy.com/media/l3q2wJsC23ikJg9xe/giphy.gif)
