### ISSUE TITLE
Release into ROS Melodic

### ISSUE THREAD

**Issue by 130s** [wg-perception/object_recognition_msgs#6]
This package is [depended by some MoveIt! packages](http://repositories.ros.org/status_page/blocked_releases_melodic.html?q=id%3D%22object_recognition_msgs%22&s=6&r=1).

Thanks!

**Comment by vrabaud** [comment]
@130s , would you mind becoming a maintainer of that package ? Thx.

**Comment by vrabaud** [comment]
Done btw.

**Comment by 130s** [comment]
Thanks @vrabaud.

I can co-maintain for release stuff. Any admin please give me a write access here and release repos. Thanks in advance.
